### ISSUE TITLE
Different MIP and MRO scores for same input -SMETANA

### ISSUE THREAD

**Issue by NTDevika** [cdanielmachado/smetana#10]
Dear Daniel,
I am running Smetana  - "smetana Lactococcus_raffinolactis_strain_WiKim0068.xml V_harveyi_QT520.xml --mediadb constrained_media_Treh.tsv  --flavor cobra -o TREHALOSE"

I am getting different results when I am executing  this commands with the same set of inputs ----  MIP and MRO score.
community	medium	size	mip	mro
all	complete	2	2	0.64

community	medium	size	mip	mro
all	complete	2	1	0.8333333333333334

What would be the reason?
Can you please help me out to sort out this issue.

Thank You

-- 
Best Regards
N.T.Devika

**Comment by cdanielmachado** [comment]
Hi Devika,

The method is deterministic so this should not happen.

Does this happen if you run the same code two consecutive times? What happens if you run multiple times?

Please add the flag `--debug` when you run the method. This will output an extra table with debug information including the minimal media for the whole community and each species.

Best regards,
Daniel

**Comment by NTDevika** [comment]
Yes, when I run the same command consecutive times I got different score for MIP & MRO.
Even I tried including --debug option.
![Smetana_Debug](https://user-images.githubusercontent.com/29056867/84568883-2710b380-ada0-11ea-93ab-12b49b829439.jpg)
![Smetana_Running_Same_Command_multiple_Times](https://user-images.githubusercontent.com/29056867/84568887-2d9f2b00-ada0-11ea-9e2d-233cf1d07d8b.jpg)

**Comment by cdanielmachado** [comment]
Ok, I think I see what is happening. The minimal medium composition for the community has a degenerate solution, there are different media with the same number of compounds. For some reason, the solver doesn't always return the same solution. I think it is because some heuristics are applied by the MILP solver. 

The medium for the community is then used to calculate the minimal media for each species, which is constrained to a subset of the original medium. Since the latter is not the same between simulations, the species-specific media also differ, which can result in different values for MIP and MRO.

My suggestion is that you use the option `--molweight`. This will minimize the total mass of the compounds in the media, which is less prone to degenerate solutions.

**Comment by NTDevika** [comment]
Thanks Daniel !!
 Including --molweight option Worked out.

**Comment by cdanielmachado** [comment]
That's great :)
