### ISSUE TITLE
SCS and MPS from detailed analysis are always 1

### ISSUE THREAD

**Issue by nigiord** [cdanielmachado/smetana#14]
Hi @cdanielmachado and thank you for providing SMETANA,

```
>>> import smetana
>>> smetana.__version__
'1.2.0'
```

I currently have pairs of interacting microbial genomes (predicted from another analysis). I wanted to use SMETANA on those pairs to see if they exhibit more putative exchanges than randoms pairs, and maybe dissect which kind of metabolites are involved.

What I did was run `smetana --detailed` independently on each pair of SBML, then concatenate the results into a list of putative interactions. I have several questions regarding this analysis.

- Out of the 38k interactions that were predicted, I noticed that all the SCS and MPS scores were always 1 (only MUS changed, and thus SMETANA was always equal to MUS given how it's calculated). Is that something normal?
![image](https://user-images.githubusercontent.com/4519487/105472899-c08c3600-5c9c-11eb-86ea-09386b0c6d79.png)

- I thought this might be related to the kind of medium that was used by default. I tried manually setting it to another medium provided by SMETANA, but I'm never able to get a solution whichever medium I use. Looking at the code, I understood that "minimal" in the result table wasn't referring to the minimal medium from mediadb, but that a custom minimal medium was build independently for each analysis (hence, for each pair), using a dependency from the reframed package. Could you describe what are the conditions applied to this minimal medium? Is there a way to recover it as an extra output of the analysis? 

- When I look at the list of compounds exchanged, I see that a lot of interactions are dummy elements that I would expect would be provided by the medium (h2o for instance). And for a significant part of those predicted interactions, the smetana score is very high (close to 1). The way I understood it, the smetana score should be usable to filter those kind of artifactual cross-feeding interactions. Do you have an idea about what could be happening?

Thank you in advance for your help.

Best regards,
−Nils

**Comment by cdanielmachado** [comment]
Hi Nils,

Here are the answers to the three questions:

- MPS is always binary (species can or cannot produce the compound). SCS depends on the number of species in the community. It estimates how much a species depends on another. Since you only have two species, each receiver species will either depend on the donor species or not. If you had more species, we could have the case that in 60% of simulations it depends on one donor species, and 40% it depends on another. This explains why in this case only MUS will vary.

- If no medium is provided during simulation, a suitable minimal medium is calculated during runtime, this will simply minimize the total number of nutrients required for the community to survive. If you provide your own minimal media, it is possible that it is not sufficient for the community to grow. Unfortunately, I did not implement an option to export this calculated medium. 

-  Yes, you can (and should) exclude this kind of compounds using the option `--exclude` and provide a file with compounds you want to ignore. [Here is an example](https://github.com/cdanielmachado/smetana/blob/master/tests/data/inorganic.txt), just add more compounds as you find appropriate.

Best regards,
Daniel
