### ISSUE TITLE
Compare MRO and MIP across samples

### ISSUE THREAD

**Issue by chenyj8** [cdanielmachado/smetana#16]
Hi,

This is a question rather than an issue. How to compare MRO and MIP across samples with different number of genomes? 

From my understanding, MIP would increase if the number of genome in a sample increase, but I am not sure if it is true for MRO as well. That is, can I divide the MRO and MIP by the number of genomes to obtain normalized MRO and MIP and compare these values across samples?

**Comment by cdanielmachado** [comment]
Hi, 

That is a very good question. 

- In principle, MRO should be independent of community size, because it is already a normalized metric (varies between 0 and 1).
- MIP grows with community size, and it should be ok to normalize it by community size, but one has to be careful with the interpretation of the results there, if comparing communities of different sizes.

If you look at Fig 2 and Fig 3 of the original SMETANA publication, you can see the variation in MRO and MIP/(community size) across different samples:

https://www.pnas.org/content/112/20/6449/tab-figures-data
